from graphics import *
win = GraphWin("Okno grafiky",1366,1001)
anOval = Oval(Point(100,200), Point(300,400))
centerPoint = anOval.getCenter()
cornerPoint = anOval.getP1()
anOval.setOutline('green')
anOval.setWidth(5)
aRectangle = Rectangle(Point(100,300), Point(400,700))
centerPoint = aRectangle.getCenter()
cornerPoint = aRectangle.getP1()
aRectangle.setOutline('red')
aRectangle.setWidth(5)
anOval.draw(win)
aRectangle.draw(win)
win.getMouse()
win.close()